### ISSUE TITLE
[crash] NoSuchMethodError for Android 2.2

### ISSUE THREAD

**Issue by manasouza** [manasouza/ContactNumberSearch#21]
Validate this error on AVD with Android 2.2

Reported on: https://play.google.com/apps/publish/?dev_acc=14210271903223439191#ErrorClusterDetailsPlace:p=br.com.mls.contactnumbersearch&et=CRASH&lr=LAST_7_DAYS&ecn=java.lang.NoSuchMethodError&tf=NumberSearchActivity.java&tc=br.com.mls.contactnumbersearch.NumberSearchActivity&tm=getPhoneContactList&nid&an&c&s=new_status_desc&ed=1476907605770

StackTrace:
`java.lang.RuntimeException: An error occured while executing doInBackground()
    at android.os.AsyncTask$3.done(AsyncTask.java:200)
    at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
    at java.util.concurrent.FutureTask.run(FutureTask.java:137)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1068)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:561)
    at java.lang.Thread.run(Thread.java:1096)
Caused by: java.lang.NoSuchMethodError: java.lang.String.isEmpty
    at br.com.mls.contactnumbersearch.NumberSearchActivity.getPhoneContactList(NumberSearchActivity.java:184)
    at br.com.mls.contactnumbersearch.NumberSearchActivity$2.doInBackground(NumberSearchActivity.java:82)
    at br.com.mls.contactnumbersearch.NumberSearchActivity$2.doInBackground(NumberSearchActivity.java:1)
    at android.os.AsyncTask$2.call(AsyncTask.java:185)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
    ... 4 more`

**Comment by manasouza** [comment]
New Updates excluded API level 8
There's only one retained APK with support at least to API level 9
